version: '2'
services:
  web:
    image: nginx:1.21-alpine
    expose:
      - "80"
    ports: 
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - exo
  exo:
    image: exoplatform/exo-community
    environment:
      EXO_PROXY_VHOST: localhost
      EXO_PROXY_PORT: 80
      EXO_DB_HOST: mysql
      EXO_PROXY_SSL: "false"
      EXO_DB_TYPE: mysql
      EXO_DB_NAME: exo
      EXO_DB_USER: exo
      EXO_DB_PASSWORD: my-secret-pw
      EXO_MONGO_HOST: mongo
      EXO_ADDONS_LIST: exo-chat:$${CHAT_VERSION}
      EXO_JVM_LOG_GC_ENABLED: "true"
      EXO_ES_HOST: es
      
    volumes:
      - exo_data:/srv/exo
      - exo_logs:/var/log/exo
    depends_on:
      - mysql
      - mongo
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-super-secret-pw
      MYSQL_DATABASE: exo
      MYSQL_USER: exo
      MYSQL_PASSWORD: my-secret-pw
    volumes:
      - mysql_data:/var/lib/mysql
  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db:rw
  es:
    image: exoplatform/elasticsearch:2.0.3
    volumes:
      - search_data:/usr/share/elasticsearch/data:rw
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx2048m
      - node.name=exo
      - cluster.name=exo
      - cluster.initial_master_nodes=exo
      - network.host=_site_         
volumes:
  exo_data:
  exo_logs:
  mysql_data:
  mongo_data:
